### ISSUE TITLE
License and Copyright infringement

### ISSUE THREAD

**Issue by phisch** [StarPlatin4m/.files#2]
Although this isn't the correct repository, you don't seem to react to the pull request on the correct one, and you don't have any contact information anywhere on your profile, this is why i am trying to reach you here now:

When you forked phocus/gtk, you accepted the MIT license, which is a very permissive one. The only condition is to not remove or alter the license and copyright notice it comes with though. Unfortunately you deleted it, which is an infringement on this license.

Please take care of the issue and merge the pull request: https://github.com/StarPlatin4m/gtk/pull/1

**Comment by phisch** [comment]
Feel free to delete this issue afterwards.

**Comment by StarPlatin4m** [comment]
Done
